# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Control(object):
    def setupUi(self, Control):
        Control.setObjectName("Control")
        Control.resize(731, 489)
        Control.setStyleSheet("background-color: #2498db")
        self.verticalLayout = QtWidgets.QVBoxLayout(Control)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TabWidget = QtWidgets.QTabWidget(Control)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.TabWidget.setFont(font)
        self.TabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabWidget.setObjectName("TabWidget")
        self.Navigation = QtWidgets.QWidget()
        self.Navigation.setObjectName("Navigation")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Navigation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.Navigation)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Start_Stop = QtWidgets.QPushButton(self.frame)
        self.Start_Stop.setStyleSheet("font: 18pt \" Courier New\"; color:black; background-color: #5ADBFF; border-radius: 5px 5px 5px 5px")
        self.Start_Stop.setObjectName("Start_Stop")
        self.verticalLayout_3.addWidget(self.Start_Stop)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setMinimumSize(QtCore.QSize(0, 60))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setMinimumSize(QtCore.QSize(0, 60))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_3.addWidget(self.doubleSpinBox)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.TabWidget.addTab(self.Navigation, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Manual = QtWidgets.QPushButton(self.frame_2)
        self.Manual.setObjectName("Manual")
        self.verticalLayout_7.addWidget(self.Manual)
        self.Autonomous = QtWidgets.QPushButton(self.frame_2)
        self.Autonomous.setObjectName("Autonomous")
        self.verticalLayout_7.addWidget(self.Autonomous)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.TabWidget.addTab(self.tab_3, "")
        self.Safety = QtWidgets.QWidget()
        self.Safety.setObjectName("Safety")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Safety)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.Safety)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.frame_3)
        self.widget.setObjectName("widget")
        self.EmStop = QtWidgets.QPushButton(self.widget)
        self.EmStop.setGeometry(QtCore.QRect(110, 100, 251, 171))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EmStop.setFont(font)
        self.EmStop.setStyleSheet("background-color: rgb(255, 0, 0); border-radius: 50px;")
        self.EmStop.setObjectName("EmStop")
        self.verticalLayout_6.addWidget(self.widget)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.TabWidget.addTab(self.Safety, "")
        self.verticalLayout.addWidget(self.TabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Control)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Control)
        self.TabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Control.accept)
        self.buttonBox.rejected.connect(Control.reject)
        QtCore.QMetaObject.connectSlotsByName(Control)

    def retranslateUi(self, Control):
        _translate = QtCore.QCoreApplication.translate
        Control.setWindowTitle(_translate("Control", "Controls"))
        self.Start_Stop.setText(_translate("Control", "Start/Stop"))
        self.label_23.setText(_translate("Control", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">Direction Control</span></p>"))
        self.label_22.setText(_translate("Control", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">Speed Control</span></p>"))
        self.pushButton_4.setText(_translate("Control", "Set Velocity"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Navigation), _translate("Control", "Navigation"))
        self.Manual.setText(_translate("Control", "Manual Mode"))
        self.Autonomous.setText(_translate("Control", "Autonomous Mode"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_3), _translate("Control", "Mode Control"))
        self.EmStop.setText(_translate("Control", "Emergency Shutdown"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Safety), _translate("Control", "Safety"))
