# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vehicle_Diagnostics.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

import sys
import os
import math
from math import ceil, trunc,isnan
import json
import jsonpickle
#import pandas as pd
from pandas import read_excel
import re
import sqlite3
import openpyxl
from bs4 import BeautifulSoup as Soup
import paho.mqtt.client as mqtt
from PyQt5 import QtCore, uic
from PyQt5.QtCore import Qt, QRegExp, QThread, pyqtSignal
from PyQt5.QtGui import QRegExpValidator, QFont, QColor
from PyQt5.QtGui import QPainter, QPen, QBrush, QFont
from PyQt5.QtCore import Qt, QPointF, QTimer
from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QMessageBox, QWidget, QTreeWidget, QTreeWidgetItem, QFileDialog,
    QComboBox, QSpinBox, QHeaderView, QDialog, QTextEdit, QLabel, QLCDNumber, QVBoxLayout
)
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_Vehicle_Diagnostics(object):
    def setupUi(self, Vehicle_Diagnostics):
        Vehicle_Diagnostics.setObjectName("Vehicle_Diagnostics")
        Vehicle_Diagnostics.resize(824, 847)
        Vehicle_Diagnostics.setStyleSheet("background-color: #2498db")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Vehicle_Diagnostics)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Vehicle_Diagnostics_Tabs = QtWidgets.QTabWidget(Vehicle_Diagnostics)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.Vehicle_Diagnostics_Tabs.setFont(font)
        self.Vehicle_Diagnostics_Tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Vehicle_Diagnostics_Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Vehicle_Diagnostics_Tabs.setObjectName("Vehicle_Diagnostics_Tabs")
        self.Navigation_Motion = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Navigation_Motion.sizePolicy().hasHeightForWidth())
        self.Navigation_Motion.setSizePolicy(sizePolicy)
        self.Navigation_Motion.setObjectName("Navigation_Motion")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Navigation_Motion)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.Navigation_Motion)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 782, 743))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(0, 60))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label.setStyleSheet("font: 18pt \" Courier New\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(60, 60))
        self.label_2.setStyleSheet("font: 18pt \" Courier New\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.YPosition = QtWidgets.QLabel(self.frame)
        self.YPosition.setMinimumSize(QtCore.QSize(50, 50))
        self.YPosition.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(" Courier New")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.YPosition.setFont(font)
        self.YPosition.setAutoFillBackground(False)
        self.YPosition.setStyleSheet("font: 18pt \" Courier New\"; color:white; background-color: rgb(16, 17, 151); border-radius: 5px 5px 5px 5px")
        self.YPosition.setText("")
        self.YPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.YPosition.setObjectName("YPosition")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.YPosition)
        self.XPosition = QtWidgets.QLabel(self.frame)
        self.XPosition.setMinimumSize(QtCore.QSize(0, 50))
        self.XPosition.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(" Courier New")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.XPosition.setFont(font)
        self.XPosition.setStyleSheet("font: 18pt \" Courier New\"; color:white; background-color: rgb(16, 17, 151); border-radius: 5px 5px 5px 5px")
        self.XPosition.setText("")
        self.XPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.XPosition.setObjectName("XPosition")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.XPosition)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setMinimumSize(QtCore.QSize(0, 60))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.Compass = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Compass.sizePolicy().hasHeightForWidth())
        self.Compass.setSizePolicy(sizePolicy)
        self.Compass.setObjectName("Compass")
        self.verticalLayout.addWidget(self.Compass)
        self.Rotation = QtWidgets.QLabel(self.frame)
        self.Rotation.setMinimumSize(QtCore.QSize(0, 50))
        self.Rotation.setStyleSheet("font: 18pt \" Courier New\"; color:white; background-color: rgb(16, 17, 151); border-radius: 5px 5px 5px 5px")
        self.Rotation.setText("")
        self.Rotation.setAlignment(QtCore.Qt.AlignCenter)
        self.Rotation.setObjectName("Rotation")
        self.verticalLayout.addWidget(self.Rotation)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSpacing(2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setMinimumSize(QtCore.QSize(0, 60))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_21)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(60, 60))
        self.label_4.setStyleSheet("font: 18pt \" Courier New\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Velocity = QtWidgets.QLabel(self.frame)
        self.Velocity.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(" Courier New")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Velocity.setFont(font)
        self.Velocity.setStyleSheet("font: 18pt \" Courier New\"; color:white; background-color: rgb(16, 17, 151); border-radius: 5px 5px 5px 5px")
        self.Velocity.setText("")
        self.Velocity.setAlignment(QtCore.Qt.AlignCenter)
        self.Velocity.setObjectName("Velocity")
        self.horizontalLayout_7.addWidget(self.Velocity)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setMinimumSize(QtCore.QSize(60, 60))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setStyleSheet("font: 18pt \" Courier New\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.formLayout_3.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_3.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.verticalLayout_4.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.Vehicle_Diagnostics_Tabs.addTab(self.Navigation_Motion, "")
        self.Operational_Mode = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Operational_Mode.sizePolicy().hasHeightForWidth())
        self.Operational_Mode.setSizePolicy(sizePolicy)
        self.Operational_Mode.setObjectName("Operational_Mode")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Operational_Mode)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.Operational_Mode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setSpacing(2)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setMinimumSize(QtCore.QSize(0, 60))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_11)
        self.ControlStatus = QtWidgets.QLabel(self.frame_2)
        self.ControlStatus.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(" Courier New")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ControlStatus.setFont(font)
        self.ControlStatus.setAutoFillBackground(False)
        self.ControlStatus.setStyleSheet("font: 18pt \" Courier New\"; color:white; background-color: rgb(16, 17, 151); border-radius: 5px 5px 5px 5px")
        self.ControlStatus.setText("")
        self.ControlStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.ControlStatus.setObjectName("ControlStatus")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ControlStatus)
        self.verticalLayout_7.addLayout(self.formLayout_5)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.Vehicle_Diagnostics_Tabs.addTab(self.Operational_Mode, "")
        self.Sensors = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sensors.sizePolicy().hasHeightForWidth())
        self.Sensors.setSizePolicy(sizePolicy)
        self.Sensors.setObjectName("Sensors")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Sensors)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Sensors)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 782, 743))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Velodyne_LiDAR = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Velodyne_LiDAR.sizePolicy().hasHeightForWidth())
        self.Velodyne_LiDAR.setSizePolicy(sizePolicy)
        self.Velodyne_LiDAR.setMinimumSize(QtCore.QSize(60, 60))
        self.Velodyne_LiDAR.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Velodyne_LiDAR.setStyleSheet("font: 18pt \" Courier New\";")
        self.Velodyne_LiDAR.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Velodyne_LiDAR.setObjectName("Velodyne_LiDAR")
        self.verticalLayout_14.addWidget(self.Velodyne_LiDAR)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_20.setObjectName("label_20")
        self.verticalLayout_12.addWidget(self.label_20)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_13.addWidget(self.label_15)
        self.Horiz_Samples = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Horiz_Samples.sizePolicy().hasHeightForWidth())
        self.Horiz_Samples.setSizePolicy(sizePolicy)
        self.Horiz_Samples.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Horiz_Samples.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.Horiz_Samples.setAlignment(QtCore.Qt.AlignCenter)
        self.Horiz_Samples.setObjectName("Horiz_Samples")
        self.verticalLayout_13.addWidget(self.Horiz_Samples)
        self.Vert_Samples = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Vert_Samples.sizePolicy().hasHeightForWidth())
        self.Vert_Samples.setSizePolicy(sizePolicy)
        self.Vert_Samples.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Vert_Samples.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.Vert_Samples.setAlignment(QtCore.Qt.AlignCenter)
        self.Vert_Samples.setObjectName("Vert_Samples")
        self.verticalLayout_13.addWidget(self.Vert_Samples)
        self.Horiz_Res = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Horiz_Res.sizePolicy().hasHeightForWidth())
        self.Horiz_Res.setSizePolicy(sizePolicy)
        self.Horiz_Res.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Horiz_Res.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.Horiz_Res.setAlignment(QtCore.Qt.AlignCenter)
        self.Horiz_Res.setObjectName("Horiz_Res")
        self.verticalLayout_13.addWidget(self.Horiz_Res)
        self.Vert_Res = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Vert_Res.sizePolicy().hasHeightForWidth())
        self.Vert_Res.setSizePolicy(sizePolicy)
        self.Vert_Res.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Vert_Res.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.Vert_Res.setAlignment(QtCore.Qt.AlignCenter)
        self.Vert_Res.setObjectName("Vert_Res")
        self.verticalLayout_13.addWidget(self.Vert_Res)
        self.MinRange = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinRange.sizePolicy().hasHeightForWidth())
        self.MinRange.setSizePolicy(sizePolicy)
        self.MinRange.setMaximumSize(QtCore.QSize(16777215, 100))
        self.MinRange.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.MinRange.setAlignment(QtCore.Qt.AlignCenter)
        self.MinRange.setObjectName("MinRange")
        self.verticalLayout_13.addWidget(self.MinRange)
        self.MaxRange = QtWidgets.QLabel(self.frame_3)
        self.MaxRange.setMaximumSize(QtCore.QSize(16777215, 100))
        self.MaxRange.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.MaxRange.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxRange.setObjectName("MaxRange")
        self.verticalLayout_13.addWidget(self.MaxRange)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.line_4 = QtWidgets.QFrame(self.frame_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_14.addWidget(self.line_4)
        self.RPLIDAR = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RPLIDAR.sizePolicy().hasHeightForWidth())
        self.RPLIDAR.setSizePolicy(sizePolicy)
        self.RPLIDAR.setMinimumSize(QtCore.QSize(60, 60))
        self.RPLIDAR.setMaximumSize(QtCore.QSize(16777215, 100))
        self.RPLIDAR.setStyleSheet("font: 18pt \" Courier New\";")
        self.RPLIDAR.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RPLIDAR.setObjectName("RPLIDAR")
        self.verticalLayout_14.addWidget(self.RPLIDAR)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_6.addWidget(self.label_23)
        self.Status = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status.sizePolicy().hasHeightForWidth())
        self.Status.setSizePolicy(sizePolicy)
        self.Status.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Status.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.Status.setAlignment(QtCore.Qt.AlignCenter)
        self.Status.setObjectName("Status")
        self.horizontalLayout_6.addWidget(self.Status)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.ModelNo = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelNo.sizePolicy().hasHeightForWidth())
        self.ModelNo.setSizePolicy(sizePolicy)
        self.ModelNo.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ModelNo.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.ModelNo.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelNo.setObjectName("ModelNo")
        self.horizontalLayout_3.addWidget(self.ModelNo)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.verticalLayout_14.addLayout(self.verticalLayout_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.HealthStatus = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HealthStatus.sizePolicy().hasHeightForWidth())
        self.HealthStatus.setSizePolicy(sizePolicy)
        self.HealthStatus.setMaximumSize(QtCore.QSize(16777215, 100))
        self.HealthStatus.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.HealthStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.HealthStatus.setObjectName("HealthStatus")
        self.horizontalLayout_5.addWidget(self.HealthStatus)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Standard_SampleRate = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Standard_SampleRate.sizePolicy().hasHeightForWidth())
        self.Standard_SampleRate.setSizePolicy(sizePolicy)
        self.Standard_SampleRate.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Standard_SampleRate.setObjectName("Standard_SampleRate")
        self.horizontalLayout_14.addWidget(self.Standard_SampleRate)
        self.Standard = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Standard.sizePolicy().hasHeightForWidth())
        self.Standard.setSizePolicy(sizePolicy)
        self.Standard.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Standard.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.Standard.setAlignment(QtCore.Qt.AlignCenter)
        self.Standard.setObjectName("Standard")
        self.horizontalLayout_14.addWidget(self.Standard)
        self.verticalLayout_14.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.Express_SampleRate = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Express_SampleRate.sizePolicy().hasHeightForWidth())
        self.Express_SampleRate.setSizePolicy(sizePolicy)
        self.Express_SampleRate.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Express_SampleRate.setObjectName("Express_SampleRate")
        self.horizontalLayout_15.addWidget(self.Express_SampleRate)
        self.Express = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Express.sizePolicy().hasHeightForWidth())
        self.Express.setSizePolicy(sizePolicy)
        self.Express.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Express.setStyleSheet("font: 18pt \" Courier New\"; color: #1f0d66;")
        self.Express.setAlignment(QtCore.Qt.AlignCenter)
        self.Express.setObjectName("Express")
        self.horizontalLayout_15.addWidget(self.Express)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.verticalLayout_9.addLayout(self.verticalLayout_14)
        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_9.addWidget(self.line_5)
        self.verticalLayout_11.addWidget(self.frame_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.scrollArea_2)
        self.Vehicle_Diagnostics_Tabs.addTab(self.Sensors, "")
        self.verticalLayout_2.addWidget(self.Vehicle_Diagnostics_Tabs)
        self.buttonBox = QtWidgets.QDialogButtonBox(Vehicle_Diagnostics)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Vehicle_Diagnostics)
        self.Vehicle_Diagnostics_Tabs.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Vehicle_Diagnostics.accept)
        self.buttonBox.rejected.connect(Vehicle_Diagnostics.reject)
        QtCore.QMetaObject.connectSlotsByName(Vehicle_Diagnostics)

    def retranslateUi(self, Vehicle_Diagnostics):
        _translate = QtCore.QCoreApplication.translate
        Vehicle_Diagnostics.setWindowTitle(_translate("Vehicle_Diagnostics", "Vehicle Diagnostics"))
        self.label_3.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">Real-Time Coordinates</span></p>"))
        self.label.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">X</span></p>"))
        self.label_2.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">Y</span></p>"))
        self.label_22.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">Compass</span></p>"))
        self.label_21.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">Motion Metrics</span></p>"))
        self.label_4.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">Velocity</span></p>"))
        self.label_7.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">m/s</span></p>"))
        self.Vehicle_Diagnostics_Tabs.setTabText(self.Vehicle_Diagnostics_Tabs.indexOf(self.Navigation_Motion), _translate("Vehicle_Diagnostics", "Navigation && Motion"))
        self.label_11.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt; font-weight:600;\">Control Status</span></p>"))
        self.Vehicle_Diagnostics_Tabs.setTabText(self.Vehicle_Diagnostics_Tabs.indexOf(self.Operational_Mode), _translate("Vehicle_Diagnostics", "Operational Mode"))
        self.Velodyne_LiDAR.setText(_translate("Vehicle_Diagnostics", "<html><head/><body><p><span style=\" font-family:\'Courier New\'; font-weight:600;\">Velodyne LiDAR</span></p>"))
        self.label_9.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt;\">Status:</span></p>"))
        self.label_12.setText(_translate("Vehicle_Diagnostics", "<html><head/><body><p><span style=\" font-family:\'Courier New\'; font-size:18pt;\">No. Horizontal Samples:</span></p></body></html>"))
        self.label_20.setText(_translate("Vehicle_Diagnostics", "<html><head/><body><p><span style=\" font-family:\'Courier New\'; font-size:18pt;\">No. Vertical Samples:</span></p></body></html>"))
        self.label_10.setText(_translate("Vehicle_Diagnostics", "<html><head/><body><p><span style=\" font-family:\'Courier New\'; font-size:18pt;\">Horizontal Angular Resolution:</span></p></body></html>"))
        self.label_14.setText(_translate("Vehicle_Diagnostics", "<html><head/><body><p><span style=\" font-family:\'Courier New\'; font-size:18pt;\">Vertical Angular Resolution:</span></p></body></html>"))
        self.label_17.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt;\">Minimum Range:</span></p></body></html>"))
        self.label_19.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt;\">Maximum Range:</span></p></body></html>"))
        self.label_15.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Horiz_Samples.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\' Courier New\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Vert_Samples.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\' Courier New\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Horiz_Res.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\' Courier New\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Vert_Res.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\' Courier New\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.MinRange.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\' Courier New\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.MaxRange.setText(_translate("Vehicle_Diagnostics", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.RPLIDAR.setText(_translate("Vehicle_Diagnostics", "<html><head/><body><p><span style=\" font-family:\'Courier New\'; font-weight:600;\">RPLIDAR</span></p>"))
        self.label_23.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt;\">Status:</span></p>"))
        self.Status.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_18.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt;\">Model:</span></p>"))
        self.ModelNo.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_24.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt;\"> Health Status:</span></p>"))
        self.HealthStatus.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Standard_SampleRate.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt;\"> Standard Sample Rate:</span></p>"))
        self.Standard.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Express_SampleRate.setText(_translate("Vehicle_Diagnostics", "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; font-size:18pt;\"> Express Sample Rate:</span></p>"))
        self.Express.setText(_translate("Vehicle_Diagnostics", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Vehicle_Diagnostics_Tabs.setTabText(self.Vehicle_Diagnostics_Tabs.indexOf(self.Sensors), _translate("Vehicle_Diagnostics", "Sensors"))
        
        self.compassWidget = CompassWidget(self.Compass)
        layout = QtWidgets.QVBoxLayout(self.Compass)
        layout.addWidget(self.compassWidget)
        
class CompassWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setMinimumSize(300, 300)
        self.angle = 0  # Current needle angle in degrees

    def setAngle(self, angle):
        """Set the angle of the compass needle."""
        self.angle = angle % 360
        self.update()

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.setRenderHint(QPainter.Antialiasing)

        # Calculate dimensions
        width = self.width()
        height = self.height()
        center = QPointF(width / 2, height / 2)
        radius = min(width, height) / 2 - 20

        # Draw outer circle
        painter.setPen(QPen(Qt.black, 2))
        painter.setBrush(QBrush(Qt.white))
        painter.drawEllipse(center, radius, radius)

        # Draw ticks and labels
        self._draw_ticks_and_labels(painter, center, radius)

        # Draw compass needle
        self._draw_needle(painter, center, radius)

    def _draw_ticks_and_labels(self, painter, center, radius):
        """Draw tick marks and direction labels."""
        font = QFont("Arial", 10)
        painter.setFont(font)

        for i in range(360):
            # Rotate the angle so that 90° corresponds to East (E) being on top
            angle_rad = math.radians(i - 90)  # Rotate by 90 degrees counterclockwise
            outer_x = center.x() + math.cos(angle_rad) * radius
            outer_y = center.y() + math.sin(angle_rad) * radius

            if i % 30 == 0:  # Major ticks
                inner_x = center.x() + math.cos(angle_rad) * (radius - 15)
                inner_y = center.y() + math.sin(angle_rad) * (radius - 15)
                painter.setPen(QPen(Qt.black, 2))
                painter.drawLine(QPointF(inner_x, inner_y), QPointF(outer_x, outer_y))

                # Draw direction labels
                if i % 90 == 0:  # Cardinal directions
                    label_radius = radius - 30
                    label_x = center.x() + math.cos(angle_rad) * label_radius
                    label_y = center.y() + math.sin(angle_rad) * label_radius

                    label = {0: "N", 90: "E", 180: "S", 270: "W"}.get(i, "")
                    painter.drawText(QPointF(label_x - 10, label_y + 10), label)
                else:  # Degree labels
                    label_radius = radius - 20
                    label_x = center.x() + math.cos(angle_rad) * label_radius
                    label_y = center.y() + math.sin(angle_rad) * label_radius

                    painter.drawText(QPointF(label_x - 10, label_y + 10), str(i))
            elif i % 5 == 0:  # Minor ticks
                inner_x = center.x() + math.cos(angle_rad) * (radius - 5)
                inner_y = center.y() + math.sin(angle_rad) * (radius - 5)
                painter.setPen(QPen(Qt.black, 1))
                painter.drawLine(QPointF(inner_x, inner_y), QPointF(outer_x, outer_y))

    def _draw_needle(self, painter, center, radius):
        """Draw the compass needle."""
        painter.setPen(Qt.NoPen)
        painter.setBrush(QBrush(Qt.red))

        needle_length = radius - 20
        # Rotate the needle by 90 degrees counterclockwise
        needle_angle = math.radians(self.angle -90)  # Rotate by 90 degrees counterclockwise

        # Needle tip
        tip_x = center.x() + math.cos(needle_angle) * needle_length
        tip_y = center.y() + math.sin(needle_angle) * needle_length

        # Needle base points
        base_left_angle = needle_angle + math.radians(150)
        base_right_angle = needle_angle - math.radians(150)
        base_left_x = center.x() + math.cos(base_left_angle) * 10
        base_left_y = center.y() + math.sin(base_left_angle) * 10
        base_right_x = center.x() + math.cos(base_right_angle) * 10
        base_right_y = center.y() + math.sin(base_right_angle) * 10

        # Draw needle
        painter.drawPolygon(QPointF(tip_x, tip_y),
                            QPointF(base_left_x, base_left_y),
                            QPointF(base_right_x, base_right_y))

        # Draw needle center
        painter.setBrush(QBrush(Qt.black))
        painter.drawEllipse(center, 5, 5)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Vehicle_Diagnostics = QtWidgets.QDialog()
    ui = Ui_Vehicle_Diagnostics()
    ui.setupUi(Vehicle_Diagnostics)
    Vehicle_Diagnostics.show()
    sys.exit(app.exec_())
